package JavaException;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

//public class Test {
	
//	public static void main (String[]args)
//	{
//		System.out.println(100/0);
//	}
//} //Exception in thread "main" java.lang.ArithmeticException: / by zero
////at JavaException.Test.main(Test.java:10)
	

	
	
	
//public class Test {
//	public static void main(String[] args) 
//	{
//		
//		int[] a={1,2,3,4,5};
//		System.out.println(a[0]);
//		System.out.println(a[4]);
//		System.out.println(a[2]);
//
//		System.out.println(a[6]);
//	}
//}    ///Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 5
////at JavaException.Test.main(Test.java:23)


	
	
	
//public class Test {
//		public static void main(String[] args) 
//		{
//			
//			String str="Sagar";
//			System.out.println(str.charAt(4));
//			System.out.println(str.charAt(6));
//		}
//	}//Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 6

	
	
//public class Test {
//	int i=10;
//	static Test t;
//	public static void main(String[] args) 
//	{
//		System.out.println(t.i);
//		System.out.println(t.i);
//	
//	}
//}///Exception in thread "main" java.lang.NullPointerException: Cannot read field "i" because "JavaException.Test.t" is null
////at JavaException.Test.main(Test.java:45)
	
	
	
//	public class Test {
//	public static void main (String[]args)
//	{
//		System.out.println("statement two");
//		System.out.println("statement one");
//	
//	try 
//		{
//		System.out.println(10/0); //AE
//	}
//	
//	catch (ArithmeticException AE)
//	
//	{
//		System.out.println("Exception raised by try block");
//		
//	}
//	System.out.println ("rest of the code");
//}}

	
	
	
	
	
		
	
	
	
	
	



